id: I60E53903
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:22:17.947145
last_modified: 2023-02-10 00:22:17.947262
source_metadata:
  title: 'Asaṅga/Maitreya: Mahāyānasūtrālaṃkāra'
  language: zh
bases:
  '2127':
    base_file: 2127.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
